services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: changeme
      MARIADB_DATABASE: nomina_poo
      MARIADB_USER: mysqluser
      MARIADB_PASSWORD: mysqlpass
    ports:
      - 3306:3306
    volumes:
      - ./admin.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1