/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nominapoo.mvc.view;

import java.util.ArrayList;
import nominapoo.mvc.controller.AdminController;
import nominapoo.mvc.model.Admin;

/**
 *
 * @author tonyc
 */
public class AdminManagerViewCRUD extends javax.swing.JFrame {

    //Controller de esta View (MVC)
    AdminController adminController = new AdminController();
    //arraylist de nuestros administradores
    ArrayList<Admin> administradores;
    //Guarda la posición del admin que está siendo mostrado
    private int index = 0;

    /**
     * Creates new form AdminManagerViewCRUD
     */
    public AdminManagerViewCRUD() {
        initComponents();
        //carga this.administradores con todos los admins de la base de datos
        this.administradores = this.adminController.getAdmins();
        this.enableAdminViewer();
        //Desabilita los botones invalidos
        this.checkValidButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_idAdmin = new javax.swing.JTextField();
        jTextField_nombreAdmin = new javax.swing.JTextField();
        jLabel_idAdmin = new javax.swing.JLabel();
        jLabel_nombreAdmin = new javax.swing.JLabel();
        jButton_anterior = new javax.swing.JButton();
        jButton_siguiente = new javax.swing.JButton();
        jButton_nuevo = new javax.swing.JButton();
        jButton_guardar = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jButton_actualizar = new javax.swing.JButton();
        jButton_guardar_actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_idAdmin.setEditable(false);
        jTextField_idAdmin.setText("jTextField1");

        jTextField_nombreAdmin.setEditable(false);
        jTextField_nombreAdmin.setText("jTextField1");

        jLabel_idAdmin.setText("id");

        jLabel_nombreAdmin.setText("nombre");

        jButton_anterior.setText("anterior");
        jButton_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_anteriorActionPerformed(evt);
            }
        });

        jButton_siguiente.setText("siguiente");
        jButton_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_siguienteActionPerformed(evt);
            }
        });

        jButton_nuevo.setText("nuevo");
        jButton_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nuevoActionPerformed(evt);
            }
        });

        jButton_guardar.setText("guardar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });

        jButton_cancelar.setText("cancelar");
        jButton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarActionPerformed(evt);
            }
        });

        jButton_eliminar.setText("elminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });

        jButton_actualizar.setText("actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });

        jButton_guardar_actualizar.setText("guardar_actualizar");
        jButton_guardar_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardar_actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_anterior)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_idAdmin)
                            .addComponent(jLabel_nombreAdmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_nombreAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jTextField_idAdmin)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_nuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_actualizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_guardar_actualizar))
                    .addComponent(jButton_siguiente))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_idAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_idAdmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_nombreAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_nombreAdmin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton_anterior))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton_siguiente)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_nuevo)
                    .addComponent(jButton_guardar)
                    .addComponent(jButton_cancelar)
                    .addComponent(jButton_eliminar)
                    .addComponent(jButton_actualizar)
                    .addComponent(jButton_guardar_actualizar))
                .addContainerGap(313, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_anteriorActionPerformed
        // TODO add your handling code here:
        index--;
        checkValidButtons();
        setViewingAdmin(administradores.get(index));
    }//GEN-LAST:event_jButton_anteriorActionPerformed

    private void jButton_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_siguienteActionPerformed
        // TODO add your handling code here:
        index++;
        checkValidButtons();
        setViewingAdmin(administradores.get(index));
    }//GEN-LAST:event_jButton_siguienteActionPerformed

    private void jButton_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nuevoActionPerformed
        // TODO add your handling code here:

        jButton_anterior.setVisible(false);
        jButton_siguiente.setVisible(false);
        jButton_nuevo.setVisible(false);
        jButton_guardar.setVisible(true);
        jButton_cancelar.setVisible(true);
        jButton_eliminar.setVisible(false);
        jButton_actualizar.setVisible(false);

        jLabel_idAdmin.setVisible(false);
        jTextField_idAdmin.setVisible(false);

        jTextField_nombreAdmin.setEditable(true);
        jTextField_nombreAdmin.setText("");


    }//GEN-LAST:event_jButton_nuevoActionPerformed

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        // TODO add your handling code here:
        Admin admin = new Admin(0, jTextField_nombreAdmin.getText());
        this.adminController.addAdmin(admin);
        this.index = 0;
        this.administradores = this.adminController.getAdmins();
        enableAdminViewer();
    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void jButton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarActionPerformed
        jTextField_idAdmin.setToolTipText("");
        enableAdminViewer();
    }//GEN-LAST:event_jButton_cancelarActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        // TODO add your handling code here:
        this.adminController.deleteAdmin(this.administradores.get(this.index));
        this.index = 0;
        this.administradores = this.adminController.getAdmins();
        enableAdminViewer();
    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
        // TODO add your handling code here:
        jButton_anterior.setVisible(false);
        jButton_siguiente.setVisible(false);
        jButton_nuevo.setVisible(false);
        jButton_guardar.setVisible(false);
        jButton_cancelar.setVisible(true);
        jButton_eliminar.setVisible(false);
        jButton_actualizar.setVisible(false);
        jButton_guardar_actualizar.setVisible(true);

        //jLabel_idAdmin.setVisible(false);
        //jTextField_idAdmin.setVisible(false);
        jTextField_idAdmin.setEditable(false);
        jTextField_idAdmin.setToolTipText("No puedes editar el id :)");

        jTextField_nombreAdmin.setEditable(true);
        jTextField_nombreAdmin.setText("");
    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jButton_guardar_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardar_actualizarActionPerformed
        // TODO add your handling code here:
        Admin admin = this.administradores.get(index);
        admin.setNombre(jTextField_nombreAdmin.getText());
        this.adminController.updateAdmin(admin);
        this.index = 0;
        this.administradores = this.adminController.getAdmins();
        enableAdminViewer();
    }//GEN-LAST:event_jButton_guardar_actualizarActionPerformed

    //Cambia al admin que se está mostrando
    private void setViewingAdmin(Admin admin) {
        jTextField_idAdmin.setText(String.valueOf(admin.getId()));
        jTextField_nombreAdmin.setText(admin.getNombre());
    }

    private void enableAdminViewer() {
        jButton_guardar.setVisible(false);
        jButton_cancelar.setVisible(false);
        jButton_anterior.setVisible(true);
        jButton_siguiente.setVisible(true);
        jButton_nuevo.setVisible(true);
        jButton_cancelar.setVisible(false);
        jButton_eliminar.setVisible(true);
        jButton_actualizar.setVisible(true);
        jButton_guardar_actualizar.setVisible(false);

        jLabel_idAdmin.setVisible(true);
        jTextField_idAdmin.setVisible(true);

        jTextField_idAdmin.setEditable(false);
        jTextField_nombreAdmin.setEditable(false);
        setViewingAdmin(administradores.get(index));
        checkValidButtons();
    }

    //Habilita/Desabilita el boton anterior/siguiente dependiendo de la posicion del admin que estamos mostrando
    private void checkValidButtons() {
        if (index == 0) {
            jButton_anterior.setEnabled(false);
        } else {
            jButton_anterior.setEnabled(true);
        }
        if (index == administradores.size() - 1) {
            jButton_siguiente.setEnabled(false);
        } else {
            jButton_siguiente.setEnabled(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminManagerViewCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminManagerViewCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminManagerViewCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminManagerViewCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminManagerViewCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JButton jButton_anterior;
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JButton jButton_guardar_actualizar;
    private javax.swing.JButton jButton_nuevo;
    private javax.swing.JButton jButton_siguiente;
    private javax.swing.JLabel jLabel_idAdmin;
    private javax.swing.JLabel jLabel_nombreAdmin;
    private javax.swing.JTextField jTextField_idAdmin;
    private javax.swing.JTextField jTextField_nombreAdmin;
    // End of variables declaration//GEN-END:variables
}
